--- 
cache: 
  directories: 
    - $HOME/.m2
    - $HOME/.sonar/cache
jdk: 
  - openjdk8
jobs: 
  include: 
    - 
      install: true
      name: "Compile curso project"
      script: "mvn package -DskipTests"
      stage: compile
    - 
      addons: ~
      install: true
      name: "SonarQube code analysis"
      organization: autimio-github
      script: 
        - "mvn sonar:sonar -Dsonar.projectKey=autimio_cursomc -Dsonar.host.url=https://sonarcloud.io"
      secure: $SONAR_TOKEN
      sonarcloud: ~
      stage: qa
      token: ~
language: java
services: 
  - docker
stages: 
  - compile
  - qa
