language: java
jdk:
  - openjdk8
services:
  - docker

stages:
  - compile
  - qa

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
jobs:
  include:
    - stage: compile
      name: "Compile curso project"
      install: true
      script: mvn package -DskipTests

    - stage: qa
          name: "SonarQube code analysis"
          install: true
          addons:
            sonarcloud:
              organization: "autimio-github"
              token:
                secure: $SONAR_TOKEN
          script:
            - mvn sonar:sonar -Dsonar.projectKey=autimio_cursomc -Dsonar.host.url=https://sonarcloud.io
